service:
  eureka:
    instance:
      hostname1:
        peer1
      port1:
        1111
      hostname2:
        peer2
      port2:
        1112
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver