eureka:
  instance:
    hostname: ${service.eureka.instance.hostname2}
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${service.eureka.instance.hostname1}:${service.eureka.instance.port1}/eureka/
server:
  port: ${service.eureka.instance.port2}