eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
server:
  port: 1111
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin