security:
  basic:
    enabled: true
  user:
    name: ${service.security.user.name}
    password: ${service.security.user.password}
spring:
  application:
    name: enreka-ha
  cloud:
    config:
      name: config
      profile: dev
      uri: http://localhost:8888/
      label: master