spring:
  application:
    name: service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:1111/eureka/
server:
  port: 8080
security:
  user:
    name: admin
    password: admin