spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
eureka:
  instance:
    hostname: localhost
    port: 1111
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
