spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:1111/eureka/
  instance:
    preferIpAddress: true
security:
  user:
    name: admin
    password: admin